# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170209_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='topic',
            name='desc',
            field=models.TextField(default='no data available'),
        ),
        migrations.AddField(
            model_name='topic',
            name='picture',
            field=models.ImageField(default='null', upload_to=b''),
        ),
        migrations.DeleteModel(
            name='description',
        ),
    ]
